### ISSUE TITLE
Ajouter src/main/environments dans le .gitignore

### ISSUE THREAD

**Issue by vincent-zurczak** [SamySalem/Projet-DevMob#1]
Pour ne pas propager sur git les futures informations sensibles que vous pourriez y mettre.

**Comment by SamySalem** [comment]
Vous voulez dire src/environments peut-être?

**Comment by vincent-zurczak** [comment]
En effet.
Au temps pour moi. ;)

**Comment by vincent-zurczak** [comment]
Il faudrait alors préciser dans votre "lisez-moi" qu'il faut créer ce fichier pour que le projet fonctionne.
Et quelles informations mettre dedans.

**Comment by SamySalem** [comment]
En fait si je comprend bien vous avez raison, j'ai ajouté src/environments a .gitignore c'est pour ça vous le voyez pas.
J'ai voulu juste confirmer que c'est le répertoire correct et pas un autre.

**Comment by SamySalem** [comment]
je voulais dire j'ai pas trouvé un dossier "main" c'est tout
