### ISSUE TITLE
Contenu du Readme

### ISSUE THREAD

**Issue by SamySalem** [SamySalem/Projet-DevMob#2]
Bonjour @vincent-zurczak
Qu'est ce qu'on doit mettre dans le Readme s'il vous plaît? Je n'ai pas une grande idée là-dessus. Merci.

**Comment by vincent-zurczak** [comment]
Bonjour,

Pour l'école elle-même, pas besoin de grand chose.
Tant qu'il y a l'APK dans les "releases", c'est bon.

Le readme en lui-même peut servir pour plus tard, notamment si vous voulez valoriser ce que vous avez fait auprès d'employeurs. De quoi parle le projet, quelles sont les fonctionnalitées et les plate-formes supportées, comment compiler le projet, etc. Pas besoin de mettre 15 pages, un petit document bien construit suffit. Mais encore une fois, c'est plus pour l'après.
